### ISSUE TITLE
no configure file

### ISSUE THREAD

**Issue by Calebtheaa** [sethtroisi/gmp-ecm#7]
I think this issue might be thought to be obvious, but I cannot seem to find a workaround to it. The installation instructions for gmp-ecm say to run a ./configure, file, but when I run it i get a file not found error. When I run the closest thing, configure.ac, I get a syntax error. Can you please help?

**Comment by sethtroisi** [comment]
I'd check out https://www.mersenneforum.org/showpost.php?p=602992&postcount=8 or https://github.com/sethtroisi/gmp-ecm/blob/master/README.dev you need to run some portion of the auto tool commands.
